In [14]:
import torch

a=torch.randn(2,3)
print(a)
print(a.shape)
b=a.unsqueeze(0)
print(b)
print(ｂ.shape)

print(c)
c=b.squeeze(0)
print(c.shape)

tensor([[-2.0126, -0.1954,  0.2089],
        [ 0.3468, -0.3687, -0.9970]])
torch.Size([2, 3])
tensor([[[-2.0126, -0.1954,  0.2089],
         [ 0.3468, -0.3687, -0.9970]]])
torch.Size([1, 2, 3])
tensor([[-0.9261, -0.1387, -0.0459],
        [-1.0748,  2.0641, -1.2162]])
torch.Size([2, 3])
